In [33]:
import numpy as np
from numpy import linalg

In [37]:
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

In [75]:
dimensions = { 'A' : A.shape, 'B' : B.shape , 'C' : C.shape, 'D' : D.shape, 'u' : u.shape, 'v' : v.shape }
dimensions

In [76]:
u_plus_v = u + v
u_plus_v

array([ 9,  7, -4,  9])

In [77]:
u_minus_v = u - v
u_minus_v 

array([ 3, -3, -2,  1])

In [78]:
alpha = 6
alpha_times_u = alpha * u 

In [79]:
alpha_times_u

array([ 36,  12, -18,  30])

In [80]:
u_dot_v = u * v

In [81]:
u_dot_v

array([18, 10,  3, 20])

In [82]:
norm_u = linalg.norm(u)

In [83]:
norm_u

8.602325267042627

In [84]:
A_plus_C = A + C

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [85]:
A_minus_Ctranspose = A - C.transpose()

In [86]:
A_minus_Ctranspose

array([[-4, -7, -3],
       [ 3,  6,  4]])

In [87]:
Ctranspose_plus_3D = C.transpose() + 3*D

In [88]:
Ctranspose_plus_3D

array([[14,  3,  3],
       [ 2,  7,  9]])

In [97]:
np.dot(B, A)

array([[-1, -5, -1],
       [ 2,  7,  4]])

In [98]:
np.dot(B, A.transpose())

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [91]:
B_times_C = B * C

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [99]:
C_times_B = np.dot(C,B)

In [103]:
B_exp_4 = B**4

In [104]:
B_exp_4

array([[1, 1],
       [0, 1]])

In [100]:
A_times_Atranspose = np.dot(A, A.transpose())

In [102]:
Dtranspose_times_D = np.dot(D.transpose(), D)